/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ole Gunnar Isager (https://sketchfab.com/FrenchBaguette)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-mug-school-project-5f5ccee1514c440887c072fae8e0d699
Title: Coffee Mug (School Project)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/coffee_mug_school_project.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mug1_Mug_0.geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mug1_Coffee_0.geometry}
        material={materials.Coffee}
      />
    </group>
  );
}

useGLTF.preload("/coffee_mug_school_project.glb");
