/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Connor Wassall (https://sketchfab.com/connorwassall)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-128k-c79a2a52d85a4c359c1944f6c638cf11
Title: Macintosh 128K
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import mac from "../assets/macintosh_128k.glb";

const Macintosh = (props) => {
  const { nodes, materials } = useGLTF(mac);
  const macRef = useRef();
  return (
    <a.group ref={macRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.028}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["Macintosh_low_01_-_Mac_0"].geometry}
              material={materials["01_-_Mac"]}
              position={[0, 1.228, 0]}
            />
          </group>
          <group
            position={[-3.862, 0, -19.728]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes["Keyboard_low_02_-_Keyboard_0"].geometry}
              material={materials["02_-_Keyboard"]}
              position={[0, 3.803, 0]}
            />
          </group>
          <group
            position={[-19.38, 1.375, -1.814]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Mouse_low__0.geometry}
              material={materials.Mouse_low__0}
              position={[-10.277, 19.734, -1.375]}
            />
          </group>
        </group>
      </group>
    </a.group>
  );
};

export default Macintosh;
