/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KOMODOZ (https://sketchfab.com/komodoz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/workshop-table-industrial-18b392ae42994abaa76dbbd7804c3514
Title: Workshop table industrial
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.017}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 0, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 0, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 49.46, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_wood_0.geometry}
            material={materials.wood}
            position={[0, 50, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 13.763, 26.881]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 11.279, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 0, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 49.46, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 11.279, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 13.763, 26.881]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 0, 30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 0, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 0, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 49.46, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 13.763, -26.881]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder015_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 13.763, -26.881]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder016_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 11.279, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 0, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 49.46, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder019_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 11.279, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder020_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 0, -30.023]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021_metal_0.geometry}
            material={materials.metal}
            position={[59.653, 13.763, -29.84]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder022_metal_0.geometry}
            material={materials.metal}
            position={[-59.653, 13.763, -29.84]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder023_metal_0.geometry}
            material={materials.metal}
            position={[-60.067, 13.763, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024_metal_0.geometry}
            material={materials.metal}
            position={[-59.645, 13.763, 2.425]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder025_metal_0.geometry}
            material={materials.metal}
            position={[-56.504, 13.763, -0.059]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_metal_0.geometry}
            material={materials.metal}
            position={[59.645, 13.763, 2.425]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_metal_0.geometry}
            material={materials.metal}
            position={[56.504, 13.763, -0.059]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/table.glb");
